const articleVocabulary = {
  5: [
    [
      { word: "substitute teaching materials", jp: "代替教材" },
      { word: "official status", jp: "正式な地位" },
      { word: "boards of education", jp: "教育委員会" },
      { word: "introduce", jp: "導入する" },
    ],
    [
      { word: "spark", jp: "引き起こす" },
      { word: "debate", jp: "議論" },
      { word: "drastically", jp: "大幅に、劇的に" },
      { word: "foundation", jp: "基盤、根幹" },
    ],
    [
      { word: "be expected to", jp: "〜する見込みである" },
      { word: "points at issue", jp: "論点、検討課題" },
      { word: "working group", jp: "作業部会" },
      { word: "scheduled", jp: "予定された" },
    ],
    [
      { word: "digitized", jp: "デジタル化された" },
      { word: "content", jp: "内容" },
      { word: "terminals", jp: "端末" },
      { word: "provided", jp: "提供された" },
    ],
    [
      { word: "review", jp: "見直し" },
      { word: "become subject to", jp: "〜の対象となる" },
      { word: "screening", jp: "検定、審査" },
      { word: "free distribution", jp: "無償給与、無料配布" },
    ],
    [
      { word: "based on", jp: "〜に基づいて" },
      { word: "compile", jp: "まとめる、編集する" },
      { word: "interim report", jp: "中間報告" },
      { word: "as early as", jp: "早ければ" },
    ],
    [
      { word: "School Education Law", jp: "学校教育法" },
      { word: "be defined as", jp: "〜と定義される" },
      { word: "in place of", jp: "〜の代わりに" },
      { word: "teaching materials", jp: "教材" },
    ],
    [
      { word: "authorized", jp: "正式に認められた" },
      { word: "official textbooks", jp: "正式な教科書" },
      { word: "completely", jp: "完全に" },
      { word: "counterparts", jp: "対応するもの、相当するもの" },
    ],
    [
      { word: "accuracy", jp: "正確性" },
      { word: "appropriateness", jp: "適切性" },
      { word: "compulsory education", jp: "義務教育" },
      { word: "be provided for free", jp: "無償で提供される" },
    ],
    [
      { word: "local government", jp: "地方自治体" },
      { word: "selective system", jp: "選択制" },
      { word: "determine", jp: "決定する" },
      { word: "distribute", jp: "配布する" },
    ],
    [
      { word: "revise", jp: "改正する" },
      { word: "fiscal", jp: "会計年度の" },
      { word: "national curriculum standards", jp: "学習指導要領" },
      { word: "aim to", jp: "〜することを目指す" },
    ],
  ],
  6: [
    [
      { word: "overtook (overtake)", jp: "上回った、追い越した" },
      { word: "electricity production", jp: "発電、電力生産" },
      { word: "renewables", jp: "再生可能エネルギー" },
      { word: "power sector", jp: "電力部門" },
    ],
    [
      { word: "gas generation", jp: "ガスによる発電" },
      { word: "declined", jp: "減少した" },
      { word: "in a row", jp: "連続して" },
      { word: "historic low", jp: "過去最低水準" },
    ],
    [
      { word: "delivered", jp: "もたらした" },
      { word: "transformation", jp: "変革、一変" },
      { word: "think tank", jp: "シンクタンク、政策研究機関" },
      { word: "rapid", jp: "急速な" },
    ],
    [
      { word: "remained", jp: "〜のままだった、維持した" },
      { word: "fastest-growing", jp: "最も成長の速い" },
      { word: "power source", jp: "電源、電力供給源" },
      { word: "nuclear", jp: "原子力" },
    ],
    [
      { word: "overall", jp: "全体として" },
      { word: "strong growth", jp: "力強い成長" },
      { word: "boosted", jp: "押し上げた" },
      { word: "share", jp: "割合、占有率" },
    ],
    [
      { word: "fossil fuels", jp: "化石燃料" },
      { word: "fallen", jp: "低下した" },
      { word: "percent", jp: "パーセント" },
    ],
    [
      { word: "surge", jp: "急増" },
      { word: "generation", jp: "発電、発電量" },
      { word: "capacity", jp: "設備容量、能力" },
      { word: "cubic meters", jp: "立方メートル" },
      { word: "imported", jp: "輸入した" },
    ],
    [
      { word: "trends", jp: "傾向" },
      { word: "widespread", jp: "広範囲に及ぶ" },
      { word: "progressing", jp: "進展している" },
      { word: "across", jp: "〜全体にわたって" },
    ],
    [
      { word: "eliminated", jp: "廃止した、取り除いた" },
      { word: "polluting", jp: "汚染を引き起こす" },
      { word: "reduced", jp: "減らした" },
      { word: "energy mix", jp: "電源構成" },
    ],
    [
      { word: "lose their grip on", jp: "〜への支配力を失う" },
      { word: "lead author", jp: "筆頭著者" },
      { word: "report", jp: "報告書" },
    ],
    [
      { word: "energy transition", jp: "エネルギー転換" },
      { word: "relegating", jp: "低い地位に追いやっている" },
      { word: "margins", jp: "周辺、重要でない位置" },
      { word: "decline", jp: "減少、衰退" },
    ],
    [
      { word: "cautioned", jp: "警告した、注意を促した" },
      { word: "remains", jp: "残っている" },
      { word: "much work", jp: "多くの課題、作業" },
    ],
    [
      { word: "accelerate", jp: "加速させる" },
      { word: "efforts", jp: "取り組み、努力" },
      { word: "particularly", jp: "特に" },
      { word: "sector", jp: "部門、分野" },
    ],
    [
      { word: "storage capacity", jp: "蓄電容量" },
      { word: "make the most of", jp: "〜を最大限に活用する" },
      { word: "by definition", jp: "本質的に、定義上" },
      { word: "intermittent", jp: "断続的な、不安定な" },
    ],
    [
      { word: "plentiful", jp: "豊富な" },
      { word: "drive down", jp: "押し下げる" },
      { word: "resulting in", jp: "〜という結果になる" },
      { word: "overabundance", jp: "過剰、あり余る量" },
      { word: "supply / demand", jp: "供給／需要" },
    ],
    [
      { word: "readily available", jp: "すぐに利用できる" },
      { word: "co-located", jp: "同じ場所に設置された、併設された" },
      { word: "producers", jp: "生産者、発電事業者" },
      { word: "avoid", jp: "避ける" },
    ],
  ],
  7: [
    [
      { word: "unlikely", jp: "ありそうにない、突飛な" },
      { word: "surge", jp: "急増、高まり" },
      { word: "national pride", jp: "国民としての誇り、愛国心" },
      { word: "pushback", jp: "反発、抵抗" },
      { word: "imposing", jp: "押しつけがましい、威圧的な" },
    ],
    [
      { word: "a snowball's chance in hell", jp: "万に一つもない可能性" },
      { word: "reacted", jp: "反応した" },
      { word: "summing up", jp: "要約して、代弁して" },
      { word: "sentiments", jp: "感情、気持ち" },
    ],
    [
      { word: "poll", jp: "世論調査" },
      { word: "citizens", jp: "国民、市民" },
      { word: "reject", jp: "拒絶する" },
      { word: "linking up with", jp: "〜と統合する、結びつく" },
    ],
    [
      { word: "pronounce", jp: "発音する" },
      { word: "parallel", jp: "緯線" },
      { word: "Celsius", jp: "摂氏" },
      { word: "Fahrenheit", jp: "華氏" },
      { word: "get used to", jp: "〜に慣れる" },
    ],
    [
      { word: "wisecracked", jp: "冗談を言った" },
      { word: "figure of speech", jp: "言葉の綾、比喩表現" },
      { word: "fretting", jp: "気をもんでいる" },
      { word: "Commonwealth", jp: "英連邦" },
      { word: "quitting", jp: "脱退すること、やめること" },
    ],
    [
      { word: "neighbours", jp: "隣人、近隣国" },
      { word: "signage", jp: "看板、標識" },
      { word: "focusing on", jp: "〜に焦点を当てて" },
      { word: "spelling", jp: "つづり" },
    ],
    [
      { word: "so-called", jp: "いわゆる" },
      { word: "groupies", jp: "熱狂的な信奉者" },
      { word: "be cool to", jp: "〜に冷ややかな反応を示す" },
      { word: "merger", jp: "合併、統合" },
    ],
    [
      { word: "be proud to", jp: "〜を誇りに思う" },
      { word: "supporter", jp: "支持者" },
      { word: "do business", jp: "商売をする、仕事をする" },
      { word: "home", jp: "故郷、居場所" },
    ],
    [
      { word: "alike", jp: "似ている" },
      { word: "economies", jp: "経済" },
      { word: "security", jp: "安全保障" },
      { word: "integrated", jp: "統合された、結びついた" },
    ],
    [
      { word: "mindset", jp: "考え方、思考様式" },
      { word: "insisted", jp: "強く主張した" },
      { word: "different", jp: "異なる" },
    ],
    [
      { word: "unified", jp: "団結させた" },
      { word: "former prime minister", jp: "元首相" },
      { word: "open letter", jp: "公開書簡" },
      { word: "insulting", jp: "侮辱的な" },
      { word: "sovereignty", jp: "主権" },
    ],
    [
      { word: "rugged", jp: "険しい" },
      { word: "against the odds", jp: "困難を乗り越えて" },
      { word: "mild-mannered", jp: "温厚な" },
      { word: "spine", jp: "芯の強さ、気骨" },
      { word: "toughness", jp: "たくましさ、強さ" },
    ],
    [
      { word: "international relations", jp: "国際関係" },
      { word: "stark", jp: "明確な、際立った" },
      { word: "professor", jp: "教授" },
      { word: "peoples", jp: "国民、人々" },
    ],
    [
      { word: "incompatible", jp: "相いれない、両立しない" },
      { word: "values", jp: "価値観" },
      { word: "become one country", jp: "一つの国になる" },
    ],
    [
      { word: "free trade", jp: "自由貿易" },
      { word: "arguably", jp: "〜と言える、議論の余地はあるが" },
      { word: "trolling", jp: "挑発的な発言、荒らし行為" },
      { word: "backlash", jp: "反発、反動" },
      { word: "reinforce", jp: "強める、補強する" },
      { word: "nationalism", jp: "ナショナリズム、国家意識" },
    ],
  ],
  8: [
    [
      { word: "aerospace engineer", jp: "航空宇宙技術者" },
      { word: "set a world record", jp: "世界記録を樹立する" },
      { word: "depressurization", jp: "減圧" },
      { word: "submerged", jp: "水中に沈められた" },
      { word: "off the coast of", jp: "〜の沖合で" },
    ],
    [
      { word: "emerged", jp: "姿を現した、出てきた" },
      { word: "in the presence of", jp: "〜の立ち会いのもとで" },
      { word: "adjudicator", jp: "審査員、判定者" },
      { word: "square-meter", jp: "平方メートルの" },
    ],
    [
      { word: "confirmed", jp: "確認した" },
      { word: "beaten the record", jp: "記録を更新した" },
      { word: "previously held", jp: "以前保持されていた" },
      { word: "underwater lodge", jp: "水中ロッジ" },
      { word: "lagoon", jp: "潟、ラグーン" },
    ],
    [
      { word: "adventure", jp: "冒険" },
      { word: "a sense of regret", jp: "名残惜しさ、後悔の気持ち" },
      { word: "capsule", jp: "カプセル" },
      { word: "leaving", jp: "出ること、去ること" },
    ],
    [
      { word: "calm down", jp: "静まる、落ち着く" },
      { word: "glowing", jp: "光っている" },
      { word: "portholes", jp: "舷窓、丸窓" },
      { word: "view", jp: "景色、眺め" },
    ],
    [
      { word: "impossible", jp: "不可能な" },
      { word: "describe", jp: "言葉で表す、描写する" },
      { word: "experience", jp: "体験する" },
      { word: "yourself", jp: "自分自身で" },
    ],
    [
      { word: "toasted", jp: "乾杯した" },
      { word: "champagne", jp: "シャンパン" },
      { word: "leaping into", jp: "〜へ飛び込むこと" },
      { word: "dry land", jp: "陸地" },
      { word: "celebratory party", jp: "祝賀パーティー" },
    ],
    [
      { word: "trappings", jp: "必要な装備、付属物" },
      { word: "modern life", jp: "現代生活" },
      { word: "exercise bike", jp: "エアロバイク" },
      { word: "capsule", jp: "カプセル" },
    ],
    [
      { word: "be attached to", jp: "〜に接続されている" },
      { word: "chamber", jp: "部屋、区画" },
      { word: "perched above", jp: "〜の上に設置された" },
      { word: "spiral staircase", jp: "らせん階段" },
      { word: "visitors", jp: "訪問者" },
    ],
    [
      { word: "solar panels", jp: "太陽光パネル" },
      { word: "surface", jp: "水面、表面" },
      { word: "backup generator", jp: "予備の発電機" },
      { word: "shower", jp: "シャワー" },
    ],
    [
      { word: "halfway through", jp: "〜の途中で" },
      { word: "endeavor", jp: "試み、努力" },
      { word: "permanently", jp: "永続的に" },
      { word: "settle", jp: "定住する" },
      { word: "journalist", jp: "記者、ジャーナリスト" },
    ],
    [
      { word: "prove", jp: "証明する" },
      { word: "viable", jp: "実行可能な、適した" },
      { word: "environment", jp: "環境" },
      { word: "human expansion", jp: "人類の拡張" },
    ],
    [
      { word: "capturing", jp: "記録すること、捉えること" },
      { word: "monitoring", jp: "監視、観察" },
      { word: "mental health", jp: "精神状態、心の健康" },
      { word: "proof", jp: "証拠、証明" },
      { word: "surface", jp: "水面" },
    ],
    [
      { word: "witnesses", jp: "証人、立会人" },
      { word: "monitoring", jp: "監視している" },
      { word: "verifying", jp: "確認している、検証している" },
      { word: "24/7", jp: "24時間週7日、常時" },
    ],
    [
      { word: "undoubtedly", jp: "間違いなく" },
      { word: "extravagant", jp: "突飛な、並外れた" },
      { word: "required", jp: "必要とした" },
      { word: "a lot of work", jp: "多くの労力" },
    ],
    [
      { word: "admirer", jp: "ファン、崇拝者" },
      { word: "sci-fi classic", jp: "SFの古典作品" },
      { word: "bedside table", jp: "ベッド脇のテーブル" },
      { word: "beneath", jp: "〜の下に" },
    ],
  ],
};

export default articleVocabulary;
