const testData = {
  5: {
    title: "Education ministry eyes digital textbooks as official schoolbooks",
    translation: [
      "情報筋によると、文部科学省は、現在紙の教科書の代替教材として使用されているデジタル教科書に、学校の教科書として使用できる正式な地位を与えることを検討している。また、各教育委員会が紙の教科書かデジタル教科書のいずれかを選べるよう、新たな制度の導入も目指しているという。",
      "この動きは、我が国の学校教育制度の根幹である教科書の形態を大きく変えることになるため、議論を呼ぶ可能性が高い。",
      "文部科学省は、火曜日に予定されている会合で、中央教育審議会の作業部会に検討課題を提示する見通しだ。",
      "デジタル教科書は紙の教科書をデジタル化したもので、内容は紙の教科書と同じである。生徒は、一人ひとりに提供される端末でデジタル化された内容を閲覧することができる。",
      "文科省は作業部会に対し、2つの主要な検討課題を提示する予定だ。第一に、デジタル教科書の位置づけを「代替教材」から「正式な学校教科書」へ見直すことを求める。これにより、デジタル教科書も国の教科書検定や無償給与の対象となる。第二に、各教育委員会が紙またはデジタルの教科書を選択できるようにする。",
      "文科省は、作業部会での議論を踏まえ、早ければ来月にも中間報告をまとめる予定だ。",
      "学校教育法では、紙の教科書が正式な学校教科書と定められ、デジタル教科書は「教科書の代わりに使用できる教材」と位置づけられている。",
      "デジタル教科書が正式な教科書として認められれば、生徒は紙の教科書を使わず、デジタル教科書だけで学習できるようになる。",
      "また、デジタル教科書も、内容の正確性や適切性に関する国の教科書検定の対象となり、義務教育段階では生徒に無償で給与されるようになる。",
      "公立学校では、教科書は学校を設置する自治体の教育委員会によって選定される。選択制が導入されれば、自治体が学校で使用する教科書とその形態を決定し、配布することになる。",
      "デジタル教科書を正式な教科書として使用するには、学校教育法の改正が必要となる。文部科学省は2026年度までに法改正を行い、次期学習指導要領に基づく授業が始まる2030年度からデジタル教科書の使用を開始したい考えだ。",
    ],
    wr2: [
      { q: "中央教育審議会のワーキンググループの会合が予定されている日", a: 3, options: [1, 2, 3, 5, 6, 7] },
      { q: "文部科学省がワーキンググループに提示する主な論点の数", a: 5, options: [2, 3, 4, 5, 6, 7] },
      { q: "教科書の位置づけを規定した法律", a: 7, options: [3, 5, 6, 7, 9, 11] },
      { q: "法律が改正された場合にデジタル教科書の正式な導入が始まる年度", a: 11, options: [5, 7, 8, 9, 10, 11] },
    ],
    wr3: {
      text: "The education ministry is considering officially recognizing digital textbooks for use in schools starting in fiscal [2030]. These textbooks are currently used only as [substitute] teaching materials. The ministry also plans to introduce a new system that would allow individual boards of education to choose between [paper] and digital formats. The move is expected to spark debate, as it could significantly change the [nature] of school textbooks. The ministry is scheduled to present the key issues to a working group of the Central [Council] for Education at a meeting on Tuesday, January 21, 2025.",
      jp: "文部科学省は、2030年度から学校でデジタル教科書を正式に使用することを検討している。現在は紙の教科書の代替教材としてのみ使われている。各教育委員会が紙とデジタルの形式を選べる新制度も導入する予定であり、教科書の在り方を大きく変える可能性があるため議論を呼ぶとみられる。主な論点は中央教育審議会の作業部会に提示される予定である。",
    },
    wr5: [
      {
        q: "Some people are likely to oppose the idea of using digital textbooks as official ones.",
        a: "T",
        jp: "一部の人々は、デジタル教科書を正式な教科書として使用する考えに反対する可能性がある。",
        reason: "第2段落。制度変更は議論を呼ぶ可能性が高い（spark debate）と書かれているため、記事の示唆と合致します。",
      },
      {
        q: "Currently, government screening is not required for digital textbooks.",
        a: "T",
        jp: "現在、デジタル教科書には国の教科書検定が求められていない。",
        reason: "第5・9段落。正式な教科書になった場合に検定の対象にもなると書かれているため、現在は対象外だと分かります。",
      },
      {
        q: "The interim report on the status of digital textbooks may be compiled in February 2025.",
        a: "T",
        jp: "デジタル教科書の位置づけに関する中間報告は、2025年2月にまとめられる可能性がある。",
        reason: "第6段落。記事は2025年1月20日付で、早ければ翌月に中間報告をまとめるとあります。",
      },
      {
        q: "Public schools are allowed to use digital textbooks as official textbooks under the current national curriculum guidelines.",
        a: "F",
        jp: "現行の学習指導要領では、公立学校はデジタル教科書を正式な教科書として使用できる。",
        reason: "第11段落。正式な教科書として使用するには学校教育法の改正が必要だとあるため、現時点では認められていません。",
      },
    ],
    ar1: [
      {
        jp: "デジタル教科書は紙の教科書の代替教材として使用されている。",
        words: ["as", "are", "for", "used", "paper textbooks", "substitute teaching materials"],
        correct: ["are", "used", "as", "substitute teaching materials", "for", "paper textbooks"],
        head: "Digital textbooks ",
        tail: ".",
      },
      {
        jp: "新制度では、各教育委員会が紙の教科書とデジタル教科書のどちらかを選択できるようになる。",
        words: ["to", "will", "allow", "choose", "either", "individual boards of education"],
        correct: ["will", "allow", "individual boards of education", "to", "choose", "either"],
        head: "A new system ",
        tail: " paper or digital textbooks.",
      },
      {
        jp: "文科省は2030年度からデジタル教科書の使用を開始することを目指している。",
        words: ["to", "aims", "from", "start", "using", "digital textbooks"],
        correct: ["aims", "to", "start", "using", "digital textbooks", "from"],
        head: "The education ministry ",
        tail: " fiscal year 2030.",
      },
      {
        jp: "デジタル教科書は生徒に無償で提供される。",
        words: ["be", "to", "for", "free", "will", "provided"],
        correct: ["will", "be", "provided", "for", "free", "to"],
        head: "Digital textbooks ",
        tail: " students.",
      },
    ],
    ar2: [
      { word: "substitute", jp: "代わりのもの、代用品", def: "a person or thing that you use or have instead of the one you normally use or have" },
      { word: "spark", jp: "引き起こす", def: "to be the cause of something, especially trouble or violence" },
      { word: "debate", jp: "議論", def: "discussion of a particular subject that often continues for a long time and in which people express different opinions" },
      { word: "transform", jp: "一変させる", def: "to completely change the appearance, form, or character of something or someone, especially in a way that improves it" },
      { word: "distribution", jp: "配布、分配", def: "the act of sharing things among a large group of people in a planned way" },
      { word: "counterpart", jp: "対応するもの、相当する人", def: "someone or something that has the same job or purpose as someone or something else in a different place" },
    ],
  },
  6: {
    title: "Solar power surpasses coal in EU for first time",
    translation: [
      "木曜日に発表された報告書によると、2024年、欧州連合（EU）の発電において太陽光発電が石炭火力発電を上回り、再生可能エネルギーの割合はEUの電力部門全体のほぼ半分に上昇した。",
      "一方、ガスによる発電は5年連続で減少し、化石燃料による発電は過去最低水準に落ち込んだと、気候変動に関するシンクタンクEmberは「欧州電力レビュー2025」で述べている。",
      "このシンクタンクは、欧州グリーンディールがEUの電力部門に重大かつ急速な変革をもたらしたと説明した。",
      "太陽光発電は2024年もEUで最も成長の速い電源となり、初めて石炭を上回った。風力発電は依然としてEUで2番目に大きな電源で、ガスを上回り、原子力に次ぐ位置にある。",
      "全体として、太陽光と風力発電の力強い成長により、再生可能エネルギーの割合は2019年の34%から47%に上昇した。",
      "化石燃料の割合は、2019年の39%から29%に低下した。",
      "風力と太陽光による発電量の急増が、化石燃料による発電が減少した主な理由である。2019年以降に増設された風力・太陽光発電設備がなければ、EUは化石燃料のガスをさらに920億立方メートル、石炭を5,500万トン輸入する必要があり、590億ユーロの費用がかかっていただろうと報告書は述べている。",
      "Emberによると、こうした傾向は欧州全域に広がっており、EUの全加盟国で太陽光発電の導入が進んでいる。",
      "現在では、EU加盟国の半数以上が、最も汚染度の高い化石燃料である石炭をすでに廃止するか、電源構成に占める割合を5%未満にまで減らしている。",
      "「化石燃料はEUのエネルギー分野で支配力を失いつつあります」と、報告書の筆頭著者クリス・ロスロー氏は述べた。",
      "「2019年に欧州グリーンディールが始まった時、EUのエネルギー転換が現在のような状況になると考えた人はほとんどいませんでした。今では風力と太陽光が石炭を周辺的な存在に追いやり、ガスの利用も減少させています」",
      "しかし、ロスロー氏は多くの課題が残っていると警告した。",
      "「特に風力発電分野で、取り組みをさらに加速させる必要があります」と同氏は述べた。",
      "「欧州の電力システムは、本質的に不安定な電源である再生可能エネルギーを最大限に活用するため、蓄電容量を増やす必要もあります」と同氏は付け加えた。",
      "2024年には、豊富な太陽光発電によって日中の電力価格が下がり、需要に対して供給が過剰だったため、価格がマイナスまたはゼロになる時間帯さえあった。",
      "すぐに利用できる解決策は、太陽光発電所に蓄電池を併設することである。これにより太陽光発電事業者は受け取る価格をより管理でき、日中に安値で電力を販売することを避けられると報告書は述べている。",
    ],
    wr2: [
      { q: "シンクタンクEmberが公表した報告書のタイトル", a: 2, options: [1, 2, 3, 4, 5, 6] },
      { q: "2019年の再生可能エネルギーの割合", a: 5, options: [2, 3, 4, 5, 6, 7] },
      { q: "2019年の化石燃料の割合", a: 6, options: [3, 4, 5, 6, 7, 8] },
      { q: "電気料金がゼロになった時間帯があった年", a: 15, options: [10, 11, 12, 14, 15, 16] },
    ],
    wr3: {
      text: "In 2019, when the European Green Deal was launched, renewables accounted for 34% of the European [Union's] electricity generation, while fossil fuels made up 39%. Since then, rapid [growth] in solar and wind power has increased the share of renewables to 47%, and solar overtook coal for the first time in 2024. Wind power remained the EU's second-largest power source - behind [nuclear] but ahead of gas. In contrast, the share of fossil fuels has dropped to 29%. More than [half] of EU countries have either phased out coal entirely or reduced its share to less than [5%] of their energy mix.",
      jp: "2019年に欧州グリーンディールが始まった時、再生可能エネルギーはEUの発電量の34%、化石燃料は39%を占めていた。その後、太陽光・風力発電が急成長して再生可能エネルギーは47%に上昇し、2024年に太陽光が初めて石炭を上回った。風力は原子力に次ぐ第2の電源である。化石燃料は29%まで低下し、EU加盟国の半数以上が石炭を廃止するか、その割合を5%未満にしている。",
    },
    wr5: [
      {
        q: "In 2023, electricity generation from gas increased in the EU.",
        a: "F",
        jp: "2023年、EUにおけるガスによる発電量が増加した。",
        reason: "第2段落。ガス発電は5年連続で減少した（declined for the fifth year in a row）とあるため誤りです。",
      },
      {
        q: "The increase in the share of solar was greater than that of wind in 2023.",
        a: "T",
        jp: "2023年における太陽光発電の増加割合は風力発電を上回った。",
        reason: "第4段落。太陽光はEUで最も成長の速い電源であり続けた（remained the EU's fastest-growing power source）とあります。",
      },
      {
        q: "Nuclear was the largest power source in the EU in 2024.",
        a: "T",
        jp: "2024年、EUにおける最大の電力供給源は原子力であった。",
        reason: "第4段落。風力は第2位で、ガスより上、原子力より下と説明されているため、原子力が最大です。",
      },
      {
        q: "Compared to coal, gas has a more negative effect on the environment.",
        a: "F",
        jp: "石炭と比べて、ガスの環境負荷は大きい。",
        reason: "第9段落。石炭は最も汚染度の高い化石燃料（the most polluting fossil fuel）とされているため誤りです。",
      },
    ],
    ar1: [
      {
        jp: "風力と太陽光がガスの衰退を促している。",
        words: ["are", "gas", "into", "solar", "decline", "pushing"],
        correct: ["solar", "are", "pushing", "gas", "into", "decline"],
        head: "Wind and ",
        tail: ".",
      },
      {
        jp: "多くのEU諸国はエネルギーミックスにおける石炭の割合を5%未満に削減している。",
        words: ["to", "cut", "less", "than", "five percent", "coal's share"],
        correct: ["cut", "coal's share", "to", "less", "than", "five percent"],
        head: "Many EU countries have ",
        tail: " of their energy mix.",
      },
      {
        jp: "供給過剰により、太陽光エネルギーの価格がゼロになった。",
        words: ["to", "to", "due", "zero", "dropped", "oversupply"],
        correct: ["dropped", "to", "zero", "due", "to", "oversupply"],
        head: "The price of solar energy ",
        tail: ".",
      },
      {
        jp: "太陽光発電所と併設された蓄電池は、太陽光発電事業者が安値で電力を販売するのを防ぐのに役立つ。",
        words: ["at", "avoid", "helps", "selling", "electricity", "solar power producers"],
        correct: ["helps", "solar power producers", "avoid", "selling", "electricity", "at"],
        head: "A battery co-located with a solar plant ",
        tail: " low prices.",
      },
    ],
    ar2: [
      { word: "overtake", jp: "追い越す、上回る", def: "to develop or increase more quickly than someone or something else and become more successful, more important, or more advanced than them" },
      { word: "coal", jp: "石炭", def: "a hard black mineral that is found below the ground and burnt to produce heat" },
      { word: "electricity", jp: "電気、電力", def: "the power that is carried by wires, cables, etc., and is used to provide light or heat, to make machines work, etc." },
      { word: "eliminate", jp: "排除する、取り除く", def: "to completely get rid of something that is unnecessary or unwanted" },
      { word: "relegate", jp: "低い地位に追いやる", def: "to give someone or something a less important position than before" },
      { word: "caution", jp: "警告する、注意を促す", def: "to warn somebody about the possible dangers or problems of something" },
    ],
  },
  7: {
    title: "'We may look easy-going, but...' Canadians veto Trump's merger plan",
    translation: [
      "価値観も違えば、つづりも違う。つまり、国も違う。ドナルド・トランプ氏がカナダを米国の51番目の州にしようとする突飛な計画は、国境の北側でナショナリズムの高まりと、しばしば押しつけがましい隣国への反発を招いている。",
      "「カナダが米国の一部になる可能性など万に一つもない」とジャスティン・トルドー首相は反応し、多くのカナダ国民の気持ちを代弁した。",
      "アンガス・リード研究所による最新の世論調査では、国民の90%が米国との統合案を拒絶していることが明らかになった。",
      "カナダ人たちはAFPに語ったりSNSに投稿したりして、49度線の北側ではZを米国人のように「ズィー」ではなく「ゼッド」と発音すること、気温を華氏ではなく摂氏で測ること、医師の診察にお金を払う習慣には絶対に慣れないことを指摘した。",
      "彼らは、米国国旗にビーバーやメープルリーフを加えることや、米国人になっても「sorry」を言葉の綾として言い続けられるかについて冗談を言う一方、カナダが英連邦を脱退することを誰がチャールズ国王に伝えるのかと気をもんだ。",
      "「永遠のneighboursであって、絶対にneighborsではない」と、バンクーバーのストリップクラブは看板で冗談を飛ばし、カナダ人が米国式のつづりに従っていないことを強調した。",
      "いわゆる「トランプ信奉者」の中にも、統合に冷ややかな反応を示す人がいる。",
      "「私はカナダ人であることをとても誇りに思っています。この国が大好きです。米国を訪れるのも好きですし、米国でビジネスをするのも楽しいです。しかし、カナダが私の故郷です」と、トロント在住のトランプ支持者ポール・コイディス氏はAFPに語った。",
      "米国人とカナダ人には、声や外見が似ていて同じ映画を見る人もおり、両国の経済と安全保障は深く統合されていると、同氏らは指摘した。",
      "「しかし、それぞれの国にはまったく異なる考え方があります」とコイディス氏は強調した。",
      "「トランプ氏は、これまでになくカナダ人を団結させた」と、ジャン・クレティエン元首相は公開書簡で述べ、トランプ氏の発言を「侮辱的」で「我々の主権に対する前例のない脅威」だと呼んだ。",
      "「私たちは、想像できる限り最も険しく厳しい地形を越えて一つの国家を築き上げ、それを非常な困難の中で成し遂げました。私たちはおおらかで温厚に見えるかもしれません。しかし、誤解しないでください。私たちには芯の強さとたくましさがあります」と同元首相は述べた。",
      "モントリオールのマギル大学で国際関係を教えるアメリカ系カナダ人のマーク・ブローリー教授は、両国民の間には明確な違いがあると述べた。",
      "「私たちには異なる価値観があり、それは一つの国になるには相いれないものです」と同教授はAFPに語った。",
      "1994年以降のカナダ・米国間の自由貿易によって両国が以前より近づいたとも言えるが、トランプ氏の挑発的な発言は反発を引き起こし、カナダのナショナリズムをさらに強めるだろうと同教授は述べた。",
    ],
    wr2: [
      { q: "併合計画に関するTrudeau首相のコメント", a: 2, options: [1, 2, 3, 4, 5, 6] },
      { q: "アンガス・リード研究所の世論調査の結果", a: 3, options: [1, 2, 3, 4, 5, 6] },
      { q: "Mark Brawley教授の勤務先", a: 13, options: [8, 9, 10, 11, 13, 14] },
      { q: "米国とカナダの自由貿易が始まった年", a: 15, options: [10, 11, 12, 13, 14, 15] },
    ],
    wr3: {
      text: "Donald Trump proposed a plan for Canada to become the [51st] state of the United States, and this proposal is triggering a surge of national [pride] among Canadians, along with a pushback against the U.S. For example, a new poll found that 90 percent of Canadians [reject] the idea of becoming part of the United States. An American-born Canadian professor of international relations noted that, while the Canada-U.S. free [trade] agreement, in place since 1994, arguably brought the two countries closer together, there remain [stark] differences between the two peoples.",
      jp: "ドナルド・トランプ氏はカナダを米国の51番目の州にする計画を提案した。これによりカナダ人の愛国心が高まり、米国への反発も起きている。世論調査では90%のカナダ人が米国との統合を拒絶した。1994年からの自由貿易協定で両国が近づいた一方、両国民の間には依然として明確な違いがある。",
    },
    wr5: [
      {
        q: "Many Canadians feel the same as Prime Minister Justin Trudeau.",
        a: "T",
        jp: "多くのカナダ人がジャスティン・トルドー首相と同じように感じている。",
        reason: "第2段落。トルドー首相の発言が多くのカナダ国民の気持ちを代弁した（summing up many Canadians' sentiments）とあります。",
      },
      {
        q: "In the United States, people do not have to pay to see a doctor.",
        a: "F",
        jp: "米国では、医者にかかるのにお金を払う必要はない。",
        reason: "第4段落。カナダ人は、医師の診察にお金を払う習慣には絶対に慣れないと述べているため、米国では支払いが必要だと分かります。",
      },
      {
        q: "The word 'sorry' is used more frequently in Canada than in the United States.",
        a: "T",
        jp: "『sorry』という言葉は、米国よりもカナダで使われる頻度が高い。",
        reason: "第5段落。米国人になってもsorryを言葉の綾として言い続けられるか冗談にしたとあるため、カナダでよく使うことが示唆されています。",
      },
      {
        q: "Free trade between Canada and the United States has been in place for more than 50 years.",
        a: "F",
        jp: "カナダと米国の間では、50年以上にわたって自由貿易が行われている。",
        reason: "第15段落。自由貿易は1994年からであり、記事時点では50年以上ではありません。",
      },
    ],
    ar1: [
      {
        jp: "彼の計画は米国に対する反発を招いている。",
        words: ["is", "to", "against", "leading", "a pushback", "the United States"],
        correct: ["is", "leading", "to", "a pushback", "against", "the United States"],
        head: "His plan ",
        tail: ".",
      },
      {
        jp: "元首相は彼の発言を彼らの国の主権に対する脅威と呼んだ。",
        words: ["to", "called", "a threat", "his remarks", "their sovereignty", "a former prime minister"],
        correct: ["a former prime minister", "called", "his remarks", "a threat", "to", "their sovereignty"],
        head: "",
        tail: ".",
      },
      {
        jp: "カナダ人は医師の診察にお金を払うことには絶対に慣れないとSNSに投稿していた。",
        words: ["to", "for", "get", "used", "paying", "a doctor visit"],
        correct: ["get", "used", "to", "paying", "for", "a doctor visit"],
        head: "Canadians posted on social media that they would never ",
        tail: ".",
      },
      {
        jp: "カナダ人は、習慣で『すみません』と言い続けられるかどうかを冗談で話していた。",
        words: ["keep", "they", "about", "could", "whether", "saying 'sorry'"],
        correct: ["about", "whether", "they", "could", "keep", "saying 'sorry'"],
        head: "Canadians joked ",
        tail: " out of habit.",
      },
    ],
    ar2: [
      { word: "border", jp: "国境、境界線", def: "the official line that separates two countries, states, or areas, or the area close to this line" },
      { word: "pushback", jp: "反発、抵抗", def: "opposition or resistance to a plan, an idea or a change" },
      { word: "neighbor", jp: "隣人、近隣国", def: "a person living near or next door to the speaker or person referred to" },
      { word: "poll", jp: "世論調査", def: "the process of finding out what people think about something by asking many people the same question, or the record of the result" },
      { word: "beaver", jp: "ビーバー", def: "a North American animal that has thick fur and a wide flat tail, and cuts down trees with its teeth" },
      { word: "merger", jp: "合併、統合", def: "the joining together of two or more companies or organizations to form one larger one" },
    ],
  },
  8: {
    title: "German man sets world record living for 120 days underwater",
    translation: [
      "ドイツ人の航空宇宙技術者が金曜日、減圧せずに水中で生活した最長時間、すなわちパナマ沖に沈められたカプセル内で120日間を過ごしたことで、世界記録の達成を祝った。",
      "59歳のルディガー・コッホ氏は、ギネス世界記録の審査員スサナ・レイエス氏が立ち会う中、海中にある約30平方メートルの住居から姿を現した。",
      "レイエス氏は、コッホ氏が、以前米国人ジョセフ・ディトゥーリ氏の持っていた記録を更新したことを確認した。ディトゥーリ氏はフロリダのラグーンにある水中ロッジで100日間生活していた。",
      "「素晴らしい冒険でした。終わってしまった今、実は名残惜しさのような気持ちもあります。ここでの時間をとても楽しみました」と、水深11メートルにあるカプセルを出たコッホ氏はAFPに語った。",
      "「周囲が静まり、暗くなって海が光り始める瞬間は美しいです」と、同氏は舷窓からの景色について述べた。",
      "「言葉では言い表せません。自分で体験しなければ分からないのです」と同氏は付け加えた。",
      "記録達成を祝うため、コッホ氏はシャンパンで乾杯して葉巻をくゆらせた後、カリブ海に飛び込んだ。ボートが同氏を拾い上げ、祝賀パーティーのために陸地へ連れていった。",
      "コッホ氏のカプセルには、ベッド、トイレ、テレビ、コンピューター、インターネット、さらにはエアロバイクまで、現代生活に必要なものがほとんどそろっていた。",
      "北パナマの海岸からボートで約15分の場所にあるカプセルは、波の上に設置された別の部屋と、狭いらせん階段を備えたチューブでつながっていた。この階段が、食料や医師を含む訪問者が下へ降りる通路となっていた。",
      "電力は水上のソーラーパネルで賄われていた。予備の発電機もあったが、シャワーはなかった。",
      "コッホ氏は、挑戦の途中で訪ねてきたAFP記者に対し、この試みが、人間の生活や、人がどこに、しかも永続的に定住できるのかについての考え方を変えることを願っていると語っていた。",
      "「私たちがここで行っているのは、海が実際に人類の拡張に適した環境であると証明することです」と同氏は述べた。",
      "カプセル内のコッホ氏の行動は4台のカメラで撮影され、日常生活の記録、精神状態の確認、そして一度も水面に出なかったことの証明に使われた。",
      "「120日を超える間、週7日、1日24時間体制で監視し、確認する証人が必要でした」とレイエス氏はAFPに語った。",
      "「この記録は間違いなく最も突飛な部類に入り、多くの労力を必要としました」とレイエス氏は付け加えた。",
      "ジュール・ヴェルヌの『海底二万里』に登場するネモ船長のファンであるコッホ氏は、この19世紀のSF古典を水中のベッドサイドテーブルに置いていた。",
    ],
    wr2: [
      { q: "Rudiger Kochさんの職業", a: 1, options: [1, 2, 3, 4, 5, 6] },
      { q: "Kochさんの前にギネス世界記録を保持していた人", a: 3, options: [1, 2, 3, 4, 5, 6] },
      { q: "海中カプセル内でのKochさんの動きを記録したカメラの台数", a: 13, options: [8, 9, 10, 11, 12, 13] },
      { q: "Kochさんの憧れの人物が登場する小説の著者", a: 16, options: [11, 12, 13, 14, 15, 16] },
    ],
    wr3: {
      text: "On January 24, 2025, German aerospace [engineer] Rudiger Koch celebrated setting a world record for the longest time living underwater without decompressing - [120] days spent in a submerged capsule. Koch's capsule was equipped with most of the comforts of [modern] life: a bed, toilet, TV, computer, the internet - even an exercise bike. Finally, he emerged from his 30-square-meter underwater home in the [presence] of a Guinness World Records adjudicator. Four cameras inside the capsule recorded his activities, providing [proof] that he never surfaced during the entire period.",
      jp: "2025年1月24日、ドイツ人航空宇宙技術者ルディガー・コッホ氏は、減圧せずに水中で過ごした最長記録を達成した。海中カプセルでの生活は120日間だった。カプセルにはベッド、トイレ、テレビ、コンピューター、インターネット、エアロバイクなど現代生活の設備が備わっていた。ギネス世界記録の審査員が立ち会う中でカプセルから出て、4台のカメラが期間中に一度も水面へ出なかったことを証明した。",
    },
    wr5: [
      {
        q: "Rudiger Koch started living underwater at the end of August, 2025.",
        a: "F",
        jp: "ルディガー・コッホ氏は2025年8月末に水中での生活を始めた。",
        reason: "第1段落と記事日付。2025年1月24日までに120日間を終えているため、2025年8月開始ではありません。",
      },
      {
        q: "Koch lived underwater for one month longer than Joseph Dituri.",
        a: "F",
        jp: "コッホ氏はジョセフ・ディトゥーリ氏より1か月長く水中で過ごした。",
        reason: "第1・3段落。コッホ氏は120日、ディトゥーリ氏は100日なので差は20日であり、1か月ではありません。",
      },
      {
        q: "While Koch was living underwater, he spoke with visitors such as a doctor and a journalist.",
        a: "T",
        jp: "水中生活中に、コッホ氏は医師やジャーナリストといった訪問者と話をした。",
        reason: "第9段落で医師などの訪問者が降りられたこと、第11段落でAFP記者が訪問したことが示されています。",
      },
      {
        q: "Koch wanted to prove that humans could live underwater.",
        a: "T",
        jp: "コッホ氏は、人間が水中で生活できることを証明したいと考えていた。",
        reason: "第11・12段落。人間が永続的に定住できる場所への考え方を変え、海が人類拡張に適した環境だと証明したいと述べています。",
      },
    ],
    ar1: [
      {
        jp: "ドイツ人の航空宇宙技術者が、パナマ沖の海中カプセルで120日間を過ごした。",
        words: ["in", "off", "spent", "120 days", "the coast", "a submerged capsule"],
        correct: ["spent", "120 days", "in", "a submerged capsule", "off", "the coast"],
        head: "A German aerospace engineer ",
        tail: " of Panama.",
      },
      {
        jp: "彼は祝賀パーティーのためにボートで陸地へ運ばれた。",
        words: ["to", "for", "him", "took", "dry land", "a celebratory party"],
        correct: ["took", "him", "to", "dry land", "for", "a celebratory party"],
        head: "A boat ",
        tail: ".",
      },
      {
        jp: "狭いらせん階段が、医師を含む訪問者が下に降りるための手段となっている。",
        words: ["for", "down", "provides", "visitors", "a way", "a narrow spiral staircase"],
        correct: ["a narrow spiral staircase", "provides", "a way", "down", "for", "visitors"],
        head: "",
        tail: ", including doctors.",
      },
      {
        jp: "カプセル内の4台のカメラが、彼が水面に出なかったことを証明した。",
        words: ["he", "up", "to", "did", "not", "come"],
        correct: ["he", "did", "not", "come", "up", "to"],
        head: "Four cameras in the capsule provided proof that ",
        tail: " the surface.",
      },
    ],
    ar2: [
      { word: "adventure", jp: "冒険", def: "an exciting experience in which dangerous or unusual things happen" },
      { word: "regret", jp: "後悔、名残惜しさ", def: "a feeling of sadness or disappointment that you have because of something that has happened or something that you have done or not done" },
      { word: "champagne", jp: "シャンパン", def: "a French white wine with a lot of bubbles, drunk on special occasions" },
      { word: "shower", jp: "シャワー", def: "a piece of equipment producing a spray of water that you stand under to wash yourself" },
      { word: "journalist", jp: "記者、ジャーナリスト", def: "a person whose job is to collect and write news stories for newspapers, magazines, radio or television" },
      { word: "expansion", jp: "拡大、拡張", def: "an act of increasing or making something increase in size, amount or importance" },
    ],
  },
};

export default testData;
