const testData = {
  5: {
    title: "Education ministry eyes digital textbooks as official schoolbooks",
    wr2: [
      { q: "中央教育審議会のワーキンググループの会合が予定されている日", a: 3, options: [1, 2, 3, 5, 6, 7] },
      { q: "文部科学省がワーキンググループに提示する主な論点の数", a: 5, options: [2, 3, 4, 5, 6, 7] },
      { q: "教科書の位置づけを規定した法律", a: 7, options: [3, 5, 6, 7, 9, 11] },
      { q: "法律が改正された場合にデジタル教科書の正式な導入が始まる年度", a: 11, options: [5, 7, 8, 9, 10, 11] },
    ],
    wr3: {
      text: "The education ministry is considering officially recognizing digital textbooks for use in schools starting in fiscal [2030]. These textbooks are currently used only as [substitute] teaching materials. The ministry also plans to introduce a new system that would allow individual boards of education to choose between [paper] and digital formats. The move is expected to spark debate, as it could significantly change the [nature] of school textbooks. The ministry is scheduled to present the key issues to a working group of the Central [Council] for Education at a meeting on Tuesday, January 21, 2025.",
      jp: "文部科学省は、2030年度から学校でデジタル教科書を正式に使用することを検討している。現在は紙の教科書の代替教材としてのみ使われている。各教育委員会が紙とデジタルの形式を選べる新制度も導入する予定であり、教科書の在り方を大きく変える可能性があるため議論を呼ぶとみられる。主な論点は中央教育審議会の作業部会に提示される予定である。",
    },
    wr5: [
      {
        q: "Some people are likely to oppose the idea of using digital textbooks as official ones.",
        a: "T",
        jp: "一部の人々は、デジタル教科書を正式な教科書として使用する考えに反対する可能性がある。",
        reason: "第2段落。制度変更は議論を呼ぶ可能性が高い（spark debate）と書かれているため、記事の示唆と合致します。",
      },
      {
        q: "Currently, government screening is not required for digital textbooks.",
        a: "T",
        jp: "現在、デジタル教科書には国の教科書検定が求められていない。",
        reason: "第5・9段落。正式な教科書になった場合に検定の対象にもなると書かれているため、現在は対象外だと分かります。",
      },
      {
        q: "The interim report on the status of digital textbooks may be compiled in February 2025.",
        a: "T",
        jp: "デジタル教科書の位置づけに関する中間報告は、2025年2月にまとめられる可能性がある。",
        reason: "第6段落。記事は2025年1月20日付で、早ければ翌月に中間報告をまとめるとあります。",
      },
      {
        q: "Public schools are allowed to use digital textbooks as official textbooks under the current national curriculum guidelines.",
        a: "F",
        jp: "現行の学習指導要領では、公立学校はデジタル教科書を正式な教科書として使用できる。",
        reason: "第11段落。正式な教科書として使用するには学校教育法の改正が必要だとあるため、現時点では認められていません。",
      },
    ],
    ar1: [
      {
        jp: "デジタル教科書は紙の教科書の代替教材として使用されている。",
        words: ["as", "are", "for", "used", "paper textbooks", "substitute teaching materials"],
        correct: ["are", "used", "as", "substitute teaching materials", "for", "paper textbooks"],
        head: "Digital textbooks ",
        tail: ".",
      },
      {
        jp: "新制度では、各教育委員会が紙の教科書とデジタル教科書のどちらかを選択できるようになる。",
        words: ["to", "will", "allow", "choose", "either", "individual boards of education"],
        correct: ["will", "allow", "individual boards of education", "to", "choose", "either"],
        head: "A new system ",
        tail: " paper or digital textbooks.",
      },
      {
        jp: "文科省は2030年度からデジタル教科書の使用を開始することを目指している。",
        words: ["to", "aims", "from", "start", "using", "digital textbooks"],
        correct: ["aims", "to", "start", "using", "digital textbooks", "from"],
        head: "The education ministry ",
        tail: " fiscal year 2030.",
      },
      {
        jp: "デジタル教科書は生徒に無償で提供される。",
        words: ["be", "to", "for", "free", "will", "provided"],
        correct: ["will", "be", "provided", "for", "free", "to"],
        head: "Digital textbooks ",
        tail: " students.",
      },
    ],
    ar2: [
      { word: "substitute", jp: "代わりのもの、代用品", def: "a person or thing that you use or have instead of the one you normally use or have" },
      { word: "spark", jp: "引き起こす", def: "to be the cause of something, especially trouble or violence" },
      { word: "debate", jp: "議論", def: "discussion of a particular subject that often continues for a long time and in which people express different opinions" },
      { word: "transform", jp: "一変させる", def: "to completely change the appearance, form, or character of something or someone, especially in a way that improves it" },
      { word: "distribution", jp: "配布、分配", def: "the act of sharing things among a large group of people in a planned way" },
      { word: "counterpart", jp: "対応するもの、相当する人", def: "someone or something that has the same job or purpose as someone or something else in a different place" },
    ],
  },
  6: {
    title: "Solar power surpasses coal in EU for first time",
    wr2: [
      { q: "シンクタンクEmberが公表した報告書のタイトル", a: 2, options: [1, 2, 3, 4, 5, 6] },
      { q: "2019年の再生可能エネルギーの割合", a: 5, options: [2, 3, 4, 5, 6, 7] },
      { q: "2019年の化石燃料の割合", a: 6, options: [3, 4, 5, 6, 7, 8] },
      { q: "電気料金がゼロになった時間帯があった年", a: 15, options: [10, 11, 12, 14, 15, 16] },
    ],
    wr3: {
      text: "In 2019, when the European Green Deal was launched, renewables accounted for 34% of the European [Union's] electricity generation, while fossil fuels made up 39%. Since then, rapid [growth] in solar and wind power has increased the share of renewables to 47%, and solar overtook coal for the first time in 2024. Wind power remained the EU's second-largest power source - behind [nuclear] but ahead of gas. In contrast, the share of fossil fuels has dropped to 29%. More than [half] of EU countries have either phased out coal entirely or reduced its share to less than [5%] of their energy mix.",
      jp: "2019年に欧州グリーンディールが始まった時、再生可能エネルギーはEUの発電量の34%、化石燃料は39%を占めていた。その後、太陽光・風力発電が急成長して再生可能エネルギーは47%に上昇し、2024年に太陽光が初めて石炭を上回った。風力は原子力に次ぐ第2の電源である。化石燃料は29%まで低下し、EU加盟国の半数以上が石炭を廃止するか、その割合を5%未満にしている。",
    },
    wr5: [
      {
        q: "In 2023, electricity generation from gas increased in the EU.",
        a: "F",
        jp: "2023年、EUにおけるガスによる発電量が増加した。",
        reason: "第2段落。ガス発電は5年連続で減少した（declined for the fifth year in a row）とあるため誤りです。",
      },
      {
        q: "The increase in the share of solar was greater than that of wind in 2023.",
        a: "T",
        jp: "2023年における太陽光発電の増加割合は風力発電を上回った。",
        reason: "第4段落。太陽光はEUで最も成長の速い電源であり続けた（remained the EU's fastest-growing power source）とあります。",
      },
      {
        q: "Nuclear was the largest power source in the EU in 2024.",
        a: "T",
        jp: "2024年、EUにおける最大の電力供給源は原子力であった。",
        reason: "第4段落。風力は第2位で、ガスより上、原子力より下と説明されているため、原子力が最大です。",
      },
      {
        q: "Compared to coal, gas has a more negative effect on the environment.",
        a: "F",
        jp: "石炭と比べて、ガスの環境負荷は大きい。",
        reason: "第9段落。石炭は最も汚染度の高い化石燃料（the most polluting fossil fuel）とされているため誤りです。",
      },
    ],
    ar1: [
      {
        jp: "風力と太陽光がガスの衰退を促している。",
        words: ["are", "gas", "into", "solar", "decline", "pushing"],
        correct: ["solar", "are", "pushing", "gas", "into", "decline"],
        head: "Wind and ",
        tail: ".",
      },
      {
        jp: "多くのEU諸国はエネルギーミックスにおける石炭の割合を5%未満に削減している。",
        words: ["to", "cut", "less", "than", "five percent", "coal's share"],
        correct: ["cut", "coal's share", "to", "less", "than", "five percent"],
        head: "Many EU countries have ",
        tail: " of their energy mix.",
      },
      {
        jp: "供給過剰により、太陽光エネルギーの価格がゼロになった。",
        words: ["to", "to", "due", "zero", "dropped", "oversupply"],
        correct: ["dropped", "to", "zero", "due", "to", "oversupply"],
        head: "The price of solar energy ",
        tail: ".",
      },
      {
        jp: "太陽光発電所と併設された蓄電池は、太陽光発電事業者が安値で電力を販売するのを防ぐのに役立つ。",
        words: ["at", "avoid", "helps", "selling", "electricity", "solar power producers"],
        correct: ["helps", "solar power producers", "avoid", "selling", "electricity", "at"],
        head: "A battery co-located with a solar plant ",
        tail: " low prices.",
      },
    ],
    ar2: [
      { word: "overtake", jp: "追い越す、上回る", def: "to develop or increase more quickly than someone or something else and become more successful, more important, or more advanced than them" },
      { word: "coal", jp: "石炭", def: "a hard black mineral that is found below the ground and burnt to produce heat" },
      { word: "electricity", jp: "電気、電力", def: "the power that is carried by wires, cables, etc., and is used to provide light or heat, to make machines work, etc." },
      { word: "eliminate", jp: "排除する、取り除く", def: "to completely get rid of something that is unnecessary or unwanted" },
      { word: "relegate", jp: "低い地位に追いやる", def: "to give someone or something a less important position than before" },
      { word: "caution", jp: "警告する、注意を促す", def: "to warn somebody about the possible dangers or problems of something" },
    ],
  },
  7: {
    title: "'We may look easy-going, but...' Canadians veto Trump's merger plan",
    wr2: [
      { q: "併合計画に関するTrudeau首相のコメント", a: 2, options: [1, 2, 3, 4, 5, 6] },
      { q: "アンガス・リード研究所の世論調査の結果", a: 3, options: [1, 2, 3, 4, 5, 6] },
      { q: "Mark Brawley教授の勤務先", a: 13, options: [8, 9, 10, 11, 13, 14] },
      { q: "米国とカナダの自由貿易が始まった年", a: 15, options: [10, 11, 12, 13, 14, 15] },
    ],
    wr3: {
      text: "Donald Trump proposed a plan for Canada to become the [51st] state of the United States, and this proposal is triggering a surge of national [pride] among Canadians, along with a pushback against the U.S. For example, a new poll found that 90 percent of Canadians [reject] the idea of becoming part of the United States. An American-born Canadian professor of international relations noted that, while the Canada-U.S. free [trade] agreement, in place since 1994, arguably brought the two countries closer together, there remain [stark] differences between the two peoples.",
      jp: "ドナルド・トランプ氏はカナダを米国の51番目の州にする計画を提案した。これによりカナダ人の愛国心が高まり、米国への反発も起きている。世論調査では90%のカナダ人が米国との統合を拒絶した。1994年からの自由貿易協定で両国が近づいた一方、両国民の間には依然として明確な違いがある。",
    },
    wr5: [
      {
        q: "Many Canadians feel the same as Prime Minister Justin Trudeau.",
        a: "T",
        jp: "多くのカナダ人がジャスティン・トルドー首相と同じように感じている。",
        reason: "第2段落。トルドー首相の発言が多くのカナダ国民の気持ちを代弁した（summing up many Canadians' sentiments）とあります。",
      },
      {
        q: "In the United States, people do not have to pay to see a doctor.",
        a: "F",
        jp: "米国では、医者にかかるのにお金を払う必要はない。",
        reason: "第4段落。カナダ人は、医師の診察にお金を払う習慣には絶対に慣れないと述べているため、米国では支払いが必要だと分かります。",
      },
      {
        q: "The word 'sorry' is used more frequently in Canada than in the United States.",
        a: "T",
        jp: "『sorry』という言葉は、米国よりもカナダで使われる頻度が高い。",
        reason: "第5段落。米国人になってもsorryを言葉の綾として言い続けられるか冗談にしたとあるため、カナダでよく使うことが示唆されています。",
      },
      {
        q: "Free trade between Canada and the United States has been in place for more than 50 years.",
        a: "F",
        jp: "カナダと米国の間では、50年以上にわたって自由貿易が行われている。",
        reason: "第15段落。自由貿易は1994年からであり、記事時点では50年以上ではありません。",
      },
    ],
    ar1: [
      {
        jp: "彼の計画は米国に対する反発を招いている。",
        words: ["is", "to", "against", "leading", "a pushback", "the United States"],
        correct: ["is", "leading", "to", "a pushback", "against", "the United States"],
        head: "His plan ",
        tail: ".",
      },
      {
        jp: "元首相は彼の発言を彼らの国の主権に対する脅威と呼んだ。",
        words: ["to", "called", "a threat", "his remarks", "their sovereignty", "a former prime minister"],
        correct: ["a former prime minister", "called", "his remarks", "a threat", "to", "their sovereignty"],
        head: "",
        tail: ".",
      },
      {
        jp: "カナダ人は医師の診察にお金を払うことには絶対に慣れないとSNSに投稿していた。",
        words: ["to", "for", "get", "used", "paying", "a doctor visit"],
        correct: ["get", "used", "to", "paying", "for", "a doctor visit"],
        head: "Canadians posted on social media that they would never ",
        tail: ".",
      },
      {
        jp: "カナダ人は、習慣で『すみません』と言い続けられるかどうかを冗談で話していた。",
        words: ["keep", "they", "about", "could", "whether", "saying 'sorry'"],
        correct: ["about", "whether", "they", "could", "keep", "saying 'sorry'"],
        head: "Canadians joked ",
        tail: " out of habit.",
      },
    ],
    ar2: [
      { word: "border", jp: "国境、境界線", def: "the official line that separates two countries, states, or areas, or the area close to this line" },
      { word: "pushback", jp: "反発、抵抗", def: "opposition or resistance to a plan, an idea or a change" },
      { word: "neighbor", jp: "隣人、近隣国", def: "a person living near or next door to the speaker or person referred to" },
      { word: "poll", jp: "世論調査", def: "the process of finding out what people think about something by asking many people the same question, or the record of the result" },
      { word: "beaver", jp: "ビーバー", def: "a North American animal that has thick fur and a wide flat tail, and cuts down trees with its teeth" },
      { word: "merger", jp: "合併、統合", def: "the joining together of two or more companies or organizations to form one larger one" },
    ],
  },
  8: {
    title: "German man sets world record living for 120 days underwater",
    wr2: [
      { q: "Rudiger Kochさんの職業", a: 1, options: [1, 2, 3, 4, 5, 6] },
      { q: "Kochさんの前にギネス世界記録を保持していた人", a: 3, options: [1, 2, 3, 4, 5, 6] },
      { q: "海中カプセル内でのKochさんの動きを記録したカメラの台数", a: 13, options: [8, 9, 10, 11, 12, 13] },
      { q: "Kochさんの憧れの人物が登場する小説の著者", a: 16, options: [11, 12, 13, 14, 15, 16] },
    ],
    wr3: {
      text: "On January 24, 2025, German aerospace [engineer] Rudiger Koch celebrated setting a world record for the longest time living underwater without decompressing - [120] days spent in a submerged capsule. Koch's capsule was equipped with most of the comforts of [modern] life: a bed, toilet, TV, computer, the internet - even an exercise bike. Finally, he emerged from his 30-square-meter underwater home in the [presence] of a Guinness World Records adjudicator. Four cameras inside the capsule recorded his activities, providing [proof] that he never surfaced during the entire period.",
      jp: "2025年1月24日、ドイツ人航空宇宙技術者ルディガー・コッホ氏は、減圧せずに水中で過ごした最長記録を達成した。海中カプセルでの生活は120日間だった。カプセルにはベッド、トイレ、テレビ、コンピューター、インターネット、エアロバイクなど現代生活の設備が備わっていた。ギネス世界記録の審査員が立ち会う中でカプセルから出て、4台のカメラが期間中に一度も水面へ出なかったことを証明した。",
    },
    wr5: [
      {
        q: "Rudiger Koch started living underwater at the end of August, 2025.",
        a: "F",
        jp: "ルディガー・コッホ氏は2025年8月末に水中での生活を始めた。",
        reason: "第1段落と記事日付。2025年1月24日までに120日間を終えているため、2025年8月開始ではありません。",
      },
      {
        q: "Koch lived underwater for one month longer than Joseph Dituri.",
        a: "F",
        jp: "コッホ氏はジョセフ・ディトゥーリ氏より1か月長く水中で過ごした。",
        reason: "第1・3段落。コッホ氏は120日、ディトゥーリ氏は100日なので差は20日であり、1か月ではありません。",
      },
      {
        q: "While Koch was living underwater, he spoke with visitors such as a doctor and a journalist.",
        a: "T",
        jp: "水中生活中に、コッホ氏は医師やジャーナリストといった訪問者と話をした。",
        reason: "第9段落で医師などの訪問者が降りられたこと、第11段落でAFP記者が訪問したことが示されています。",
      },
      {
        q: "Koch wanted to prove that humans could live underwater.",
        a: "T",
        jp: "コッホ氏は、人間が水中で生活できることを証明したいと考えていた。",
        reason: "第11・12段落。人間が永続的に定住できる場所への考え方を変え、海が人類拡張に適した環境だと証明したいと述べています。",
      },
    ],
    ar1: [
      {
        jp: "ドイツ人の航空宇宙技術者が、パナマ沖の海中カプセルで120日間を過ごした。",
        words: ["in", "off", "spent", "120 days", "the coast", "a submerged capsule"],
        correct: ["spent", "120 days", "in", "a submerged capsule", "off", "the coast"],
        head: "A German aerospace engineer ",
        tail: " of Panama.",
      },
      {
        jp: "彼は祝賀パーティーのためにボートで陸地へ運ばれた。",
        words: ["to", "for", "him", "took", "dry land", "a celebratory party"],
        correct: ["took", "him", "to", "dry land", "for", "a celebratory party"],
        head: "A boat ",
        tail: ".",
      },
      {
        jp: "狭いらせん階段が、医師を含む訪問者が下に降りるための手段となっている。",
        words: ["for", "down", "provides", "visitors", "a way", "a narrow spiral staircase"],
        correct: ["a narrow spiral staircase", "provides", "a way", "down", "for", "visitors"],
        head: "",
        tail: ", including doctors.",
      },
      {
        jp: "カプセル内の4台のカメラが、彼が水面に出なかったことを証明した。",
        words: ["he", "up", "to", "did", "not", "come"],
        correct: ["he", "did", "not", "come", "up", "to"],
        head: "Four cameras in the capsule provided proof that ",
        tail: " the surface.",
      },
    ],
    ar2: [
      { word: "adventure", jp: "冒険", def: "an exciting experience in which dangerous or unusual things happen" },
      { word: "regret", jp: "後悔、名残惜しさ", def: "a feeling of sadness or disappointment that you have because of something that has happened or something that you have done or not done" },
      { word: "champagne", jp: "シャンパン", def: "a French white wine with a lot of bubbles, drunk on special occasions" },
      { word: "shower", jp: "シャワー", def: "a piece of equipment producing a spray of water that you stand under to wash yourself" },
      { word: "journalist", jp: "記者、ジャーナリスト", def: "a person whose job is to collect and write news stories for newspapers, magazines, radio or television" },
      { word: "expansion", jp: "拡大、拡張", def: "an act of increasing or making something increase in size, amount or importance" },
    ],
  },
};

export default testData;
